# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secretapp', '0002_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='postid', to='secretapp.User'),
        ),
        migrations.AddField(
            model_name='secret',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='secretapp.User'),
            preserve_default=False,
        ),
    ]
